# Preprocessing data 2 (hospital2.xlsx)

In [118]:
import pandas as pd

Cargamos el conjunto de datos

In [119]:
data2 = pd.read_excel("hospital2.xlsx")

En primer lugar, vamos a observar como recibimos los datos.

In [120]:
data2.head()

patient_id  admission_id country_of_residence   age              sex  \
0         NaN           NaN                  NaN   NaN              NaN   
1  88567155.0          45.0                 T.C.  52.0  E=male K=female   
2  36069621.0         181.0                 T.C.  47.0                K   
3  57644199.0          36.0                 T.C.  36.0                K   
4  81365404.0          32.0                 T.C.  30.0                E   

  date_of_first_symptoms      admission_date  fever_temperature  \
0                    NaT                 NaT                NaN   
1    2021-03-01 00:00:00 2021-03-01 00:00:00               37.3   
2    2021-03-01 08:38:00 2021-03-01 08:38:00               38.0   
3    2021-03-01 08:39:00 2021-03-01 08:39:00               37.5   
4    2021-03-01 09:25:00 2021-03-01 09:25:00               37.8   

   oxygen_saturation  history_of_fever  ...  chronic_hematologic_disease  \
0                NaN               NaN  ...                            0   
1               -1.0               0.0  ...                            0   
2               95.0               1.0  ...                            0   
3               88.0               0.0  ...                            0   
4               87.0               1.0  ...                            0   

   AIDS_HIV  diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
0         0                         0                         0   
1         0                         0                         0   
2         0                         0                         0   
3         0                         0                         0   
4         0                         0                         0   

   rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
0                       0         0             0        0            0   
1                       0         0             0        0            0   
2                       0         0             0        0            0   
3                       0         0             0        0            0   
4                       0         0             0        0            0   

   PCR_result  
0         NaN  
1    positive  
2    positive  
3    positive  
4    positive  

[5 rows x 54 columns]

En primer lugar, observamos que la primera fila está compuesta de valores nulos, por tanto, vamos a eliminarla ya que no nos da ningún tipo de información.

In [121]:
data2.drop(index=0, inplace=True)

## ¿Columnas redundantes?

Al igual que con el dataset anterior, vamos a ver si existen columnas redundantes. 

En este caso, observamos que las columnas "date_of_first_symptoms" y "admission_date" parecen tener los mismos valores. Vamos a comprobarlo.

In [122]:
data2.loc[(data2['date_of_first_symptoms'] != data2['admission_date'])]

patient_id  admission_id country_of_residence  age  sex  \
12735         NaN           NaN                  NaN  NaN  NaN   
12736         NaN           NaN                  NaN  NaN  NaN   

      date_of_first_symptoms admission_date  fever_temperature  \
12735                    NaT            NaT                NaN   
12736                    NaT            NaT                NaN   

       oxygen_saturation  history_of_fever  ...  chronic_hematologic_disease  \
12735                NaN               NaN  ...                            0   
12736                NaN               NaN  ...                            0   

       AIDS_HIV  diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
12735         0                         0                         0   
12736         0                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
12735                       0         0             0        0            0   
12736                       0         0             0        0            0   

       PCR_result  
12735    positive  
12736    positive  

[2 rows x 54 columns]

Observamos que las únicas columnas que son diferentes son aquellas donde casi todos los valores son nulos. 

Por tanto, al igual que antes, eliminaremos la columna admission_date ya que es una columna redundante, y posteriormente inspeccionaremos estas filas de nulos.

In [123]:
data2.drop(['admission_date'], axis=1, inplace=True)

En cuanto a las filas, ya hemos encontrado 3 filas donde la mayoría de sus valores son nulos. Esta situación es anómala, por lo que vamos a ver si existen más registros así:

In [124]:
data2[data2.isna().sum(axis=1) > 2]

patient_id  admission_id country_of_residence  age  sex  \
12735         NaN           NaN                  NaN  NaN  NaN   
12736         NaN           NaN                  NaN  NaN  NaN   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
12735                    NaT                NaN                NaN   
12736                    NaT                NaN                NaN   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
12735               NaN    0.0  ...                            0         0   
12736               NaN    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
12735                         0                         0   
12736                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
12735                       0         0             0        0            0   
12736                       0         0             0        0            0   

       PCR_result  
12735    positive  
12736    positive  

[2 rows x 53 columns]

In [125]:
indices = data2[data2.isna().sum(axis=1) > 2].index.to_list()
data2.drop(indices, inplace=True)

In [126]:
data2['patient_id'] = data2['patient_id'].astype(int)

In [127]:
data2[data2.isna().sum(axis=1) > 2]

Empty DataFrame
Columns: [patient_id, admission_id, country_of_residence, age, sex, date_of_first_symptoms, fever_temperature, oxygen_saturation, history_of_fever, cough, sore_throat, runny_nose, wheezing, shortness_of_breath, lower_chest_wall_indrawing, chest_pain, conjunctivitis, lymphadenopathy, headache, loss_of_smell, loss_of_taste, fatigue_malaise, anorexia, altered_consciousness_confusion, muscle_aches, joint_pain, inability_to_walk, abdominal_pain, diarrhoea, vomiting_nausea, skin_rash, bleeding, other_symptoms, chronic_cardiac_disease, hypertension, chronic_pulmonary_disease, asthma, chronic_kidney_disease, obesity, liver_disease, asplenia, chronic_neurological_disorder, malignant_neoplasm, chronic_hematologic_disease, AIDS_HIV, diabetes_mellitus_type_1, diabetes_mellitus_type_2, rheumatologic_disorder, dementia, tuberculosis, smoking, other_risks, PCR_result]
Index: []

[0 rows x 53 columns]

### ¿Incoherencias en el género?

Observamos que el primer valor de la columna "Gender" tiene la descripción de lo que significan los valores de la columna, en vez de un valor único. Por tanto, vamos a sustituirlo. Para ello, primero veremos si existen otros casos con ese ID para así observar el género que tienen.

In [128]:
data2[data2['patient_id'] == data2['patient_id'].iloc[0]]

patient_id  admission_id country_of_residence   age              sex  \
1        88567155          45.0                 T.C.  52.0  E=male K=female   
6177     88567155          48.0                 T.C.  51.0                E   
12339    88567155          51.0                 T.C.  53.0                E   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
1        2021-03-01 00:00:00               37.3               -1.0   
6177     2021-09-19 18:48:00               37.2               95.0   
12339    2022-03-01 07:57:00               36.7               94.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
1                   0.0    0.0  ...                            0         0   
6177                1.0    0.0  ...                            0         0   
12339               1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
1                             0                         0   
6177                          0                         0   
12339                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
1                           0         0             0        0            0   
6177                        0         0             0        0            0   
12339                       0         0             0        0            0   

       PCR_result  
1        positive  
6177     positive  
12339    positive  

[3 rows x 53 columns]

Como observamos, en el caso de este paciente, se trata de un hombre, por tanto vamos a sustituir dicho valor y veremos si hay mas incoherencias en esta columna.

In [129]:
data2.loc[1, 'sex'] = 'E'

In [130]:
data2['sex'].value_counts()

sex
K    7670
E    5064
Name: count, dtype: int64

In [131]:
data2.groupby('patient_id')['sex'].nunique().value_counts()

sex
1    9423
Name: count, dtype: int64

No existen incoherencias en el género.

### ¿Incoherencias en la Edad?

En este caso, vamos a ver si existen incoherencias en la edad que debamos tratar.

In [132]:
data2.sort_values(by='date_of_first_symptoms').iloc[[0, -1]]

patient_id  admission_id country_of_residence   age sex  \
1        88567155          45.0                 T.C.  52.0   E   
12734    55408811         182.0                 T.C.  41.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
1        2021-03-01 00:00:00               37.3               -1.0   
12734    2022-03-13 17:23:00               37.4               98.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
1                   0.0    0.0  ...                            0         0   
12734               0.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
1                             0                         0   
12734                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
1                           0         0             0        0            0   
12734                       0         0             0        0            0   

       PCR_result  
1        positive  
12734    positive  

[2 rows x 53 columns]

Podemos observar que la diferencia de fechas de los síntomas nos indica que el paciente habrá podido cumplir, como máximo, dos años. Esta situación ocurriría en pacientes que se hayan hecho 2 PCRs distintas: la primera del 1 al 13 de marzo de 2021, y la segunda desde el 1 al 13 de marzo de 2022, siendo la primera fecha (MM/DD) anterior a la segunda. Veamos si estos casos existen.

In [133]:
patients_first_period = data2[data2['date_of_first_symptoms'] <= '2021-03-13']['patient_id']
patients_second_period = data2[data2['date_of_first_symptoms'] >= '2022-03-01']['patient_id']
list(set(patients_first_period) & set(patients_second_period))

[89537920, 22219078, 88567155, 81365404, 96305535]

- Paciente 1:

In [134]:
data2[(data2['patient_id'] == 89537920.0) & ((data2['date_of_first_symptoms'] <= '2021-03-13') | (data2['date_of_first_symptoms'] >= '2022-03-01'))]

patient_id  admission_id country_of_residence   age sex  \
61       89537920          12.0                 T.C.  41.0   K   
12670    89537920          16.0                 T.C.  41.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
61       2021-03-03 15:38:00               36.5               90.0   
12670    2022-03-11 09:25:00               36.7               97.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
61                  0.0    0.0  ...                            0         0   
12670               0.0    1.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
61                            0                         0   
12670                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
61                          0         0             0        0            0   
12670                       0         0             0        0            0   

       PCR_result  
61       positive  
12670    negative  

[2 rows x 53 columns]

- Paciente 2:

In [135]:
data2[(data2['patient_id'] == 22219078.0) & ((data2['date_of_first_symptoms'] <= '2021-03-13') | (data2['date_of_first_symptoms'] >= '2022-03-01'))]

patient_id  admission_id country_of_residence   age sex  \
205      22219078           4.0                 T.C.  34.0   K   
12500    22219078           7.0                 T.C.  36.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
205      2021-03-12 08:35:00               38.3               89.0   
12500    2022-03-06 09:50:00               36.8               97.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
205                 1.0    1.0  ...                            0         0   
12500               1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
205                           0                         0   
12500                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
205                         0         0             0        0            0   
12500                       0         0             0        0            0   

       PCR_result  
205      positive  
12500    positive  

[2 rows x 53 columns]

- Paciente 3:

In [136]:
data2[(data2['patient_id'] == 88567155.0) & ((data2['date_of_first_symptoms'] <= '2021-03-13') | (data2['date_of_first_symptoms'] >= '2022-03-01'))]

patient_id  admission_id country_of_residence   age sex  \
1        88567155          45.0                 T.C.  52.0   E   
12339    88567155          51.0                 T.C.  53.0   E   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
1        2021-03-01 00:00:00               37.3               -1.0   
12339    2022-03-01 07:57:00               36.7               94.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
1                   0.0    0.0  ...                            0         0   
12339               1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
1                             0                         0   
12339                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
1                           0         0             0        0            0   
12339                       0         0             0        0            0   

       PCR_result  
1        positive  
12339    positive  

[2 rows x 53 columns]

- Paciente 4:

In [137]:
data2[(data2['patient_id'] == 81365404.0) & ((data2['date_of_first_symptoms'] <= '2021-03-13') | (data2['date_of_first_symptoms'] >= '2022-03-01'))]

patient_id  admission_id country_of_residence   age sex  \
4        81365404          32.0                 T.C.  30.0   E   
12482    81365404          38.0                 T.C.  30.0   E   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
4        2021-03-01 09:25:00               37.8               87.0   
12482    2022-03-05 13:13:00               36.7               95.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
4                   1.0    1.0  ...                            0         0   
12482               0.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
4                             0                         0   
12482                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
4                           0         0             0        0            0   
12482                       0         0             0        0            0   

       PCR_result  
4        positive  
12482    positive  

[2 rows x 53 columns]

- Paciente 5:

In [138]:
data2[(data2['patient_id'] == 96305535.0) & ((data2['date_of_first_symptoms'] <= '2021-03-13') | (data2['date_of_first_symptoms'] >= '2022-03-01'))]

patient_id  admission_id country_of_residence   age sex  \
194      96305535          13.0                 T.C.  31.0   E   
12345    96305535          16.0                 T.C.  31.0   E   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
194      2021-03-11 13:29:00               38.4               95.0   
12345    2022-03-01 08:58:00               37.2               96.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
194                 0.0    0.0  ...                            0         0   
12345               0.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
194                           0                         0   
12345                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
194                         0         0             0        0            0   
12345                       0         0             0        0            0   

       PCR_result  
194      positive  
12345    positive  

[2 rows x 53 columns]

Analizando los 5 pacientes, solo 3 de ellos cumplen las condiciones que exigíamos: 89537920.0, 88567155.0, 81365404.0. Por tanto, estos 3 pacientes han cumplido, con toda seguridad, un año entre una PCR y otra. Los trataremos por separado.

Al igual que en el dataset anterior, veamos si hay incoherencias de edad y cómo son:

In [139]:
def age_incoherences_2(min_difference):
    age_diffs = data2.groupby('patient_id')['age'].agg(lambda x: x.max() - x.min())
    count = (age_diffs >= min_difference).sum()
    indexes = age_diffs[age_diffs >= min_difference].index
    return count, indexes

In [140]:
print("Diferencias de 1 o más años: ", age_incoherences_2(1)[0])
print("Diferencias de 2 o más años: ", age_incoherences_2(2)[0])
print("Diferencias de 3 o más años: ", age_incoherences_2(3)[0])

Diferencias de 1 o más años:  1642
Diferencias de 2 o más años:  793
Diferencias de 3 o más años:  159


Con esto, podemos verificar que existen aproximadamente cerca de 1000 personas cuya edad ha sido codificada erróneamente. Ante esta situación, se pueden tomar las soluciones propuestas anteriormente. En este caso, al igual que en el anterior vamos a optar por la solución A, que consiste en lo siguiente: 
La solución más básica sería poner la misma edad a todos los personas que repitan PCR. Esta podría ser la más baja, la más alta, la que esté entre las dos (si la diferencia es de 2), o la más repetida. Esta solución evitaría incoherencias de edad.

Para ello, volveremos a hacer uso de la función anterior. Concretamente, elegimos la edad más repetida en los registros de la persona.

Vamos a tomar el ejemplo donde hemos cambiado el sexo para ver si se modifican las edades correctamente.

In [141]:
data2[data2['patient_id'] == data2['patient_id'].iloc[0]]

patient_id  admission_id country_of_residence   age sex  \
1        88567155          45.0                 T.C.  52.0   E   
6177     88567155          48.0                 T.C.  51.0   E   
12339    88567155          51.0                 T.C.  53.0   E   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
1        2021-03-01 00:00:00               37.3               -1.0   
6177     2021-09-19 18:48:00               37.2               95.0   
12339    2022-03-01 07:57:00               36.7               94.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
1                   0.0    0.0  ...                            0         0   
6177                1.0    0.0  ...                            0         0   
12339               1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
1                             0                         0   
6177                          0                         0   
12339                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
1                           0         0             0        0            0   
6177                        0         0             0        0            0   
12339                       0         0             0        0            0   

       PCR_result  
1        positive  
6177     positive  
12339    positive  

[3 rows x 53 columns]

Como observamos en este caso, la edad está mal codificada ya que en marzo de 2021 el paciente tiene 52 años mientras que 6 meses después tiene 51 años. Por tanto, usaremos la moda para modificar los valores.

In [142]:
def mode_or_min(series):
    return series.mode()[0]
data2['age'] = data2.groupby('patient_id')['age'].transform(mode_or_min)

Comprobamos si se han modificado los valores.

In [143]:
data2[data2['patient_id'] == data2['patient_id'].iloc[0]]

patient_id  admission_id country_of_residence   age sex  \
1        88567155          45.0                 T.C.  51.0   E   
6177     88567155          48.0                 T.C.  51.0   E   
12339    88567155          51.0                 T.C.  51.0   E   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
1        2021-03-01 00:00:00               37.3               -1.0   
6177     2021-09-19 18:48:00               37.2               95.0   
12339    2022-03-01 07:57:00               36.7               94.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
1                   0.0    0.0  ...                            0         0   
6177                1.0    0.0  ...                            0         0   
12339               1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
1                             0                         0   
6177                          0                         0   
12339                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
1                           0         0             0        0            0   
6177                        0         0             0        0            0   
12339                       0         0             0        0            0   

       PCR_result  
1        positive  
6177     positive  
12339    positive  

[3 rows x 53 columns]

Así, podemos observar que los datos se han modificado correctamente.

Para tratar las incoherencias en aquellos 3 casos excepcionales, lo haremos manualmente. Veamos el ejemplo del paciente con ID 89537920.

In [144]:
data2[data2['patient_id'] == 89537920]

patient_id  admission_id country_of_residence   age sex  \
61       89537920          12.0                 T.C.  41.0   K   
6753     89537920          15.0                 T.C.  41.0   K   
12670    89537920          16.0                 T.C.  41.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
61       2021-03-03 15:38:00               36.5               90.0   
6753     2021-10-04 08:19:00               38.1               97.0   
12670    2022-03-11 09:25:00               36.7               97.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
61                  0.0    0.0  ...                            0         0   
6753                1.0    1.0  ...                            0         0   
12670               0.0    1.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
61                            0                         0   
6753                          0                         0   
12670                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
61                          0         0             0        0            0   
6753                        0         0             0        0            0   
12670                       0         0             0        0            0   

       PCR_result  
61       positive  
6753     negative  
12670    negative  

[3 rows x 53 columns]

Ahora mismo existe una incoherencia, pues en su 3ª PCR debería tener un año más que en la primera, como mínimo. Apliquemos esta operación con los 3 casos:

In [145]:
data2.loc[(data2['patient_id'] == 89537920) & (data2['date_of_first_symptoms'] == '2022-03-11 09:25:00'), 'age'] = 42
data2.loc[(data2['patient_id'] == 88567155) & (data2['date_of_first_symptoms'] == '2022-03-01 07:57:00'), 'age'] = 52
data2.loc[(data2['patient_id'] == 81365404) & (data2['date_of_first_symptoms'] == '2022-03-05 13:13:00'), 'age'] = 31

In [146]:
data2[data2['patient_id'] == 89537920]

patient_id  admission_id country_of_residence   age sex  \
61       89537920          12.0                 T.C.  41.0   K   
6753     89537920          15.0                 T.C.  41.0   K   
12670    89537920          16.0                 T.C.  42.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
61       2021-03-03 15:38:00               36.5               90.0   
6753     2021-10-04 08:19:00               38.1               97.0   
12670    2022-03-11 09:25:00               36.7               97.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
61                  0.0    0.0  ...                            0         0   
6753                1.0    1.0  ...                            0         0   
12670               0.0    1.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
61                            0                         0   
6753                          0                         0   
12670                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
61                          0         0             0        0            0   
6753                        0         0             0        0            0   
12670                       0         0             0        0            0   

       PCR_result  
61       positive  
6753     negative  
12670    negative  

[3 rows x 53 columns]

Ahora sí, finalmente, no existen incoherencias en la edad.

### ¿Incoherencias en la nacionalidad?

En primer lugar, para comprobar si existen incoherencias en este caso, debemos comprobar si existen registros que tienen el mismo ID pero con diferente nacionalidad. En el caso de nuestros datos, la columna se denomina "country_of_residence".

In [147]:
data2.groupby('patient_id')['country_of_residence'].nunique().value_counts()

country_of_residence
1    9394
2      29
Name: count, dtype: int64

Podemos determinar con certeza que existen 29 IDs que contienen alguna incoherencia en la nacionalidad.

In [148]:
ids_of_nationality_incoherences = data2.groupby('patient_id')['country_of_residence'].nunique().loc[lambda x: x > 1].index

In [149]:
data2.loc[data2['patient_id'].isin(ids_of_nationality_incoherences)].sort_values(by='patient_id')

patient_id  admission_id country_of_residence   age sex  \
753       1139027           8.0           Azerbaijan  17.0   K   
6381      1139027          11.0                 T.C.  17.0   K   
5952      1331997         145.0              Ireland  36.0   K   
12314     1331997         151.0                 T.C.  36.0   K   
7708      1331997         149.0                 T.C.  36.0   K   
...           ...           ...                  ...   ...  ..   
803      91145408           8.0                 T.C.  21.0   E   
10201    99454396           6.0                 T.C.  23.0   K   
2555     99454396           3.0             Pakistan  23.0   K   
12423    99454396           7.0                 T.C.  23.0   K   
3667     99454396           4.0                 T.C.  23.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
753      2021-03-29 15:37:00               38.3               79.0   
6381     2021-09-24 00:31:00               36.9               98.0   
5952     2021-09-14 08:54:00               36.3               95.0   
12314    2022-02-28 13:12:00               37.4               96.0   
7708     2021-11-01 09:43:00               39.0               96.0   
...                      ...                ...                ...   
803      2021-03-30 11:21:00               37.9               97.0   
10201    2022-01-12 14:52:00               37.0               97.0   
2555     2021-05-04 11:59:00               38.7               89.0   
12423    2022-03-03 11:00:00               38.1               97.0   
3667     2021-07-06 13:34:00               39.1               96.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
753                 1.0    0.0  ...                            0         0   
6381                1.0    0.0  ...                            0         0   
5952                1.0    0.0  ...                            0         0   
12314               1.0    0.0  ...                            0         0   
7708                1.0    1.0  ...                            0         0   
...                 ...    ...  ...                          ...       ...   
803                 1.0    0.0  ...                            0         0   
10201               1.0    1.0  ...                            0         0   
2555                0.0    0.0  ...                            0         0   
12423               0.0    0.0  ...                            0         0   
3667                1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
753                           0                         0   
6381                          0                         0   
5952                          0                         0   
12314                         0                         0   
7708                          0                         0   
...                         ...                       ...   
803                           0                         0   
10201                         0                         0   
2555                          0                         0   
12423                         0                         0   
3667                          0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
753                         0         0             0        0            0   
6381                        0         0             0        0            0   
5952                        0         0             0        1            0   
12314                       0         0             0        0            0   
7708                        0         0             0        0            0   
...                       ...       ...           ...      ...          ...   
803                         0         0             0        0            0   
10201                       0         0             0        0         

Podemos observar que en absolutamente todos se repite que un registro de la persona con nacionalidad no es T.C pero en el resto de registros es T.C que corresponde a la nacionalidad turca. Para hacerlo más sencillo, vamos a asumir que estas personas son turcas y, por tanto, vamos a cambiar los valores donde se indique lo contrario.

Como hemos comentado con el dataset anterior, esta asunción puede ser errónea pero pensamos que la nacionalidad no será un factor muy relevante en la predicción y esta simplificación permitirá evitar posibles incoherencias futuras.

In [150]:
for id in ids_of_nationality_incoherences:
    data2.loc[data2['patient_id'] == id, 'country_of_residence'] = "T.C."

In [151]:
data2.loc[data2['patient_id'].isin(ids_of_nationality_incoherences)].sort_values(by='patient_id')

patient_id  admission_id country_of_residence   age sex  \
753       1139027           8.0                 T.C.  17.0   K   
6381      1139027          11.0                 T.C.  17.0   K   
5952      1331997         145.0                 T.C.  36.0   K   
12314     1331997         151.0                 T.C.  36.0   K   
7708      1331997         149.0                 T.C.  36.0   K   
...           ...           ...                  ...   ...  ..   
803      91145408           8.0                 T.C.  21.0   E   
10201    99454396           6.0                 T.C.  23.0   K   
2555     99454396           3.0                 T.C.  23.0   K   
12423    99454396           7.0                 T.C.  23.0   K   
3667     99454396           4.0                 T.C.  23.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
753      2021-03-29 15:37:00               38.3               79.0   
6381     2021-09-24 00:31:00               36.9               98.0   
5952     2021-09-14 08:54:00               36.3               95.0   
12314    2022-02-28 13:12:00               37.4               96.0   
7708     2021-11-01 09:43:00               39.0               96.0   
...                      ...                ...                ...   
803      2021-03-30 11:21:00               37.9               97.0   
10201    2022-01-12 14:52:00               37.0               97.0   
2555     2021-05-04 11:59:00               38.7               89.0   
12423    2022-03-03 11:00:00               38.1               97.0   
3667     2021-07-06 13:34:00               39.1               96.0   

       history_of_fever  cough  ...  chronic_hematologic_disease  AIDS_HIV  \
753                 1.0    0.0  ...                            0         0   
6381                1.0    0.0  ...                            0         0   
5952                1.0    0.0  ...                            0         0   
12314               1.0    0.0  ...                            0         0   
7708                1.0    1.0  ...                            0         0   
...                 ...    ...  ...                          ...       ...   
803                 1.0    0.0  ...                            0         0   
10201               1.0    1.0  ...                            0         0   
2555                0.0    0.0  ...                            0         0   
12423               0.0    0.0  ...                            0         0   
3667                1.0    0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
753                           0                         0   
6381                          0                         0   
5952                          0                         0   
12314                         0                         0   
7708                          0                         0   
...                         ...                       ...   
803                           0                         0   
10201                         0                         0   
2555                          0                         0   
12423                         0                         0   
3667                          0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
753                         0         0             0        0            0   
6381                        0         0             0        0            0   
5952                        0         0             0        1            0   
12314                       0         0             0        0            0   
7708                        0         0             0        0            0   
...                       ...       ...           ...      ...          ...   
803                         0         0             0        0            0   
10201                       0         0             0        0         

Así, las nacionalidades donde había incoherencias se han convertido en T.C

## Transformación de columnas

Primero de todo, vamos a definir las columnas que vamos a transformar a valores numéricos. En el caso de este dataset, corresponde con las columnas "country_of_residence", "sex", "PCR_result". 

In [152]:
any_null_cols_2 = data2.columns[data2.isnull().any()]
data2[any_null_cols_2].isnull().sum()

fever_temperature    1219
oxygen_saturation       4
history_of_fever        5
bleeding               36
other_symptoms         36
PCR_result             33
dtype: int64

#### PCR_result

Vamos a empezar por la variable que vamos a predecir, el resultado de la prueba PCR. En este caso, como hemos indicado anteriormente, debemos transformarla a valores numéricos, pero primero debemos ver que hacemos con los datos nulos.

En este caso al tratarse de la variable a predecir, no tendría sentido imputar los datos nulos. Por tanto, procedemos a eliminarlos.

In [153]:
data2.dropna(subset=['PCR_result'], inplace=True)

Ahora sí, transformamos la columna. Usaremos un LabelEncoder(), importado anteriormente.

In [154]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
PCR_result_encoder = LabelEncoder()

In [155]:
data2['PCR_result'] = PCR_result_encoder.fit_transform(data2['PCR_result'])

data2['PCR_result'].value_counts()

PCR_result
1    9776
0    2925
Name: count, dtype: int64

### Country of residence

En segundo lugar, vamos a tratar la columna de nacionalidad de la misma manera con la que lo tratamos preprocesando el dataset 1. T.C. ccorresponde a Turquía. En primer lugar, vemos si las clases estaán balanceadas

In [156]:
data2['country_of_residence'].value_counts()

country_of_residence
T.C.                              12322
Azerbaijan                          138
Russia                               28
Kyrgyzstan                           20
Iraq                                 11
                                  ...  
Seychelles                            1
British Indian Ocean Territory        1
Ethiopia                              1
Nigeria                               1
Australia                             1
Name: count, Length: 67, dtype: int64

Como observamos, apreciamos que las clases no están balanceadas, la gran mayoría de pacientes son turcos.

Para una mejor aplicación de OneHotEncoder, vamos a establecer un umbral de 60 personas. Es decir, aquellos países con +60 personas se mantienen y el resto se introduce en una nueva categoría llamada "Otros".

In [157]:
countries_with_less_than_60_patients = data2['country_of_residence'].value_counts().loc[lambda x: x < 60].index

In [158]:
data2.loc[data2['country_of_residence'].isin(countries_with_less_than_60_patients), 'country_of_residence'] = "Other"

In [159]:
data2['country_of_residence'].value_counts()

country_of_residence
T.C.          12322
Other           241
Azerbaijan      138
Name: count, dtype: int64

Aunque la clase sigue desbalanceada, ahora no hay países que apenas tengan representación.

Ahora, pasamos a la transformación de la columna a datos numéricos:

In [160]:
country_of_residence_encoder = OneHotEncoder(sparse_output=False)

encoded_country_of_residence = country_of_residence_encoder.fit_transform(data2['country_of_residence'].values.reshape(-1, 1))

encoded_country_of_residence_df = pd.DataFrame(encoded_country_of_residence, columns=country_of_residence_encoder.get_feature_names_out())

data2 = data2.reset_index(drop=True)
data2 = pd.concat([data2['patient_id'], encoded_country_of_residence_df, data2.loc[:, 'age':]], axis=1)
data2

patient_id  x0_Azerbaijan  x0_Other  x0_T.C.   age sex  \
0        88567155            0.0       0.0      1.0  51.0   E   
1        36069621            0.0       0.0      1.0  47.0   K   
2        57644199            0.0       0.0      1.0  35.0   K   
3        81365404            0.0       0.0      1.0  30.0   E   
4        82027164            0.0       0.0      1.0  42.0   K   
...           ...            ...       ...      ...   ...  ..   
12696    74182927            0.0       0.0      1.0  67.0   E   
12697    63144550            0.0       0.0      1.0  58.0   E   
12698    69906416            0.0       0.0      1.0  38.0   E   
12699    51323961            0.0       0.0      1.0  45.0   E   
12700    55408811            0.0       0.0      1.0  42.0   K   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
0        2021-03-01 00:00:00               37.3               -1.0   
1        2021-03-01 08:38:00               38.0               95.0   
2        2021-03-01 08:39:00               37.5               88.0   
3        2021-03-01 09:25:00               37.8               87.0   
4        2021-03-01 09:50:00               36.9               89.0   
...                      ...                ...                ...   
12696    2022-03-13 14:45:00               36.6               95.0   
12697    2022-03-13 14:48:00               37.7               96.0   
12698    2022-03-13 15:44:00               36.9               87.0   
12699    2022-03-13 15:45:00               39.2               96.0   
12700    2022-03-13 17:23:00               37.4               98.0   

       history_of_fever  ...  chronic_hematologic_disease  AIDS_HIV  \
0                   0.0  ...                            0         0   
1                   1.0  ...                            0         0   
2                   0.0  ...                            0         0   
3                   1.0  ...                            0         0   
4                   0.0  ...                            0         0   
...                 ...  ...                          ...       ...   
12696               0.0  ...                            0         0   
12697               0.0  ...                            0         0   
12698               1.0  ...                            0         0   
12699               0.0  ...                            0         0   
12700               0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
0                             0                         0   
1                             0                         0   
2                             0                         0   
3                             0                         0   
4                             0                         0   
...                         ...                       ...   
12696                         0                         0   
12697                         0                         0   
12698                         0                         0   
12699                         0                         0   
12700                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
0                           0         0             0        0            0   
1                           0         0             0        0            0   
2                           0         0             0        0            0   
3                           0         0             0        0            0   
4                           0         0             0        0            0   
...                       ...       ...           ...      ...          ...   
12696                       0         0             0        0            0   
12697                       0         0             0        0            0   
12698                       0         0             0        0            0   
12699    

### Género

El género, es simple de transformar ya que no tiene valores nulos y son dos categorías.

In [161]:
data2['sex'].value_counts()

sex
K    7649
E    5052
Name: count, dtype: int64

Transformamos la columna, sabiendo que K = Female y E = Male

In [162]:
gender_encoder = LabelEncoder()
data2['sex'] = gender_encoder.fit_transform(data2['sex'])

In [163]:
data2

patient_id  x0_Azerbaijan  x0_Other  x0_T.C.   age  sex  \
0        88567155            0.0       0.0      1.0  51.0    0   
1        36069621            0.0       0.0      1.0  47.0    1   
2        57644199            0.0       0.0      1.0  35.0    1   
3        81365404            0.0       0.0      1.0  30.0    0   
4        82027164            0.0       0.0      1.0  42.0    1   
...           ...            ...       ...      ...   ...  ...   
12696    74182927            0.0       0.0      1.0  67.0    0   
12697    63144550            0.0       0.0      1.0  58.0    0   
12698    69906416            0.0       0.0      1.0  38.0    0   
12699    51323961            0.0       0.0      1.0  45.0    0   
12700    55408811            0.0       0.0      1.0  42.0    1   

      date_of_first_symptoms  fever_temperature  oxygen_saturation  \
0        2021-03-01 00:00:00               37.3               -1.0   
1        2021-03-01 08:38:00               38.0               95.0   
2        2021-03-01 08:39:00               37.5               88.0   
3        2021-03-01 09:25:00               37.8               87.0   
4        2021-03-01 09:50:00               36.9               89.0   
...                      ...                ...                ...   
12696    2022-03-13 14:45:00               36.6               95.0   
12697    2022-03-13 14:48:00               37.7               96.0   
12698    2022-03-13 15:44:00               36.9               87.0   
12699    2022-03-13 15:45:00               39.2               96.0   
12700    2022-03-13 17:23:00               37.4               98.0   

       history_of_fever  ...  chronic_hematologic_disease  AIDS_HIV  \
0                   0.0  ...                            0         0   
1                   1.0  ...                            0         0   
2                   0.0  ...                            0         0   
3                   1.0  ...                            0         0   
4                   0.0  ...                            0         0   
...                 ...  ...                          ...       ...   
12696               0.0  ...                            0         0   
12697               0.0  ...                            0         0   
12698               1.0  ...                            0         0   
12699               0.0  ...                            0         0   
12700               0.0  ...                            0         0   

       diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
0                             0                         0   
1                             0                         0   
2                             0                         0   
3                             0                         0   
4                             0                         0   
...                         ...                       ...   
12696                         0                         0   
12697                         0                         0   
12698                         0                         0   
12699                         0                         0   
12700                         0                         0   

       rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
0                           0         0             0        0            0   
1                           0         0             0        0            0   
2                           0         0             0        0            0   
3                           0         0             0        0            0   
4                           0         0             0        0            0   
...                       ...       ...           ...      ...          ...   
12696                       0         0             0        0            0   
12697                       0         0             0        0            0   
12698                       0         0             0        0            0 

Una vez que ya hemos tratado las columnas que eran necesarias transformar, pasamos al tratamiento de nulos.

## Tratamiento de nulos

In [164]:
any_null_cols_2 = data2.columns[data2.isnull().any()]
data2[any_null_cols_2].isnull().sum()

fever_temperature    1217
oxygen_saturation       4
history_of_fever        5
bleeding               36
other_symptoms         36
dtype: int64

Como se puede observar, únicamente tenemos cinco categorías donde abordaremos los valores nulos. Comenzaremos tratando las variables relacionadas con "other_symptoms" y "bleeding". En este caso, interpretamos que un valor nulo indica que no se ha detectado sangrado ni otros síntomas durante las pruebas. Por lo tanto, imputaremos estos valores asumiendo que no han presentado dichos síntomas.

In [165]:
data2['bleeding'].fillna(0, inplace=True)
data2['other_symptoms'].fillna(0, inplace=True)

C:\Users\usuario\AppData\Local\Temp\ipykernel_12448\916575593.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data2['bleeding'].fillna(0, inplace=True)
C:\Users\usuario\AppData\Local\Temp\ipykernel_12448\916575593.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example,

In [166]:
any_null_cols_2 = data2.columns[data2.isnull().any()]
data2[any_null_cols_2].isnull().sum()

fever_temperature    1217
oxygen_saturation       4
history_of_fever        5
dtype: int64

Una vez tratados estos, vamos a ver los nulos de "history_of_fever" ya que puede ser que tenga un valor nulo en esta columna, pero en otro momento haya tenido fiebre el paciente o tenga fiebre en ese momento y no haya sido registrado correctamente. En nuestro caso, consideraremos que un paciente tiene fiebre si su temperatura supera los 38 Cº.

In [167]:
data2[data2['history_of_fever'].isnull()].head()

patient_id  x0_Azerbaijan  x0_Other  x0_T.C.   age  sex  \
2074    93931390            0.0       0.0      1.0  45.0    0   
3059     6486188            0.0       0.0      1.0  32.0    1   
3095    69140194            0.0       0.0      1.0  33.0    0   
3101    84804508            0.0       0.0      1.0  64.0    0   
4649    52708151            0.0       0.0      1.0  35.0    1   

     date_of_first_symptoms  fever_temperature  oxygen_saturation  \
2074    2021-04-21 11:29:00               37.2               98.0   
3059    2021-06-01 00:16:00                NaN               95.0   
3095    2021-06-03 08:06:00                NaN               95.0   
3101    2021-06-03 13:53:00                NaN               89.0   
4649    2021-08-10 21:45:00               36.7               96.0   

      history_of_fever  ...  chronic_hematologic_disease  AIDS_HIV  \
2074               NaN  ...                            0         0   
3059               NaN  ...                            0         0   
3095               NaN  ...                            0         0   
3101               NaN  ...                            0         0   
4649               NaN  ...                            0         0   

      diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
2074                         0                         0   
3059                         0                         0   
3095                         0                         0   
3101                         0                         0   
4649                         0                         0   

      rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
2074                       0         0             0        0            0   
3059                       0         0             0        0            0   
3095                       0         0             0        0            0   
3101                       0         0             0        0            0   
4649                       0         0             0        0            0   

      PCR_result  
2074           1  
3059           1  
3095           1  
3101           1  
4649           0  

[5 rows x 54 columns]

Como vemos en estos 5 casos, 3 de ellos no tienen registro de temperatura de fiebre. Por tanto, vamos a ver otros registros de esos pacientes con ese ID para ver si podemos obtener algo más de información

In [168]:
ids_with_null_history_of_fever = data2[data2['history_of_fever'].isnull()]['patient_id']

# See the lines where id is in ids_with_null_history_of_fever
data2[data2['patient_id'].isin(ids_with_null_history_of_fever)].head()

patient_id  x0_Azerbaijan  x0_Other  x0_T.C.   age  sex  \
2074    93931390            0.0       0.0      1.0  45.0    0   
2856    69140194            0.0       0.0      1.0  33.0    0   
3059     6486188            0.0       0.0      1.0  32.0    1   
3095    69140194            0.0       0.0      1.0  33.0    0   
3101    84804508            0.0       0.0      1.0  64.0    0   

     date_of_first_symptoms  fever_temperature  oxygen_saturation  \
2074    2021-04-21 11:29:00               37.2               98.0   
2856    2021-05-19 08:22:00               38.0               90.0   
3059    2021-06-01 00:16:00                NaN               95.0   
3095    2021-06-03 08:06:00                NaN               95.0   
3101    2021-06-03 13:53:00                NaN               89.0   

      history_of_fever  ...  chronic_hematologic_disease  AIDS_HIV  \
2074               NaN  ...                            0         0   
2856               1.0  ...                            0         0   
3059               NaN  ...                            0         0   
3095               NaN  ...                            0         0   
3101               NaN  ...                            0         0   

      diabetes_mellitus_type_1  diabetes_mellitus_type_2  \
2074                         0                         0   
2856                         0                         0   
3059                         0                         0   
3095                         0                         0   
3101                         0                         0   

      rheumatologic_disorder  dementia  tuberculosis  smoking  other_risks  \
2074                       0         0             0        0            0   
2856                       0         0             0        0            0   
3059                       0         0             0        0            0   
3095                       0         0             0        0            0   
3101                       0         0             0        0            0   

      PCR_result  
2074           1  
2856           1  
3059           1  
3095           1  
3101           1  

[5 rows x 54 columns]

In [169]:
data2['history_of_fever'].value_counts()

history_of_fever
1.0    9818
0.0    2878
Name: count, dtype: int64

Vemos que hay un caso donde ya ha tenido fiebre antes, por tanto el valor del historial de fiebre para ese paciente debe ser uno ya que lo ha tenido. Para los otros casos, como no se sabe la temperatura, y donde sabemos las temperaturas no superan el umbral de fiebre, añadimos que no ha tenido historial de fiebre.

In [170]:
data2.loc[data2['patient_id'] == 69140194, 'history_of_fever'] = 1
data2['history_of_fever'].fillna(0 , inplace=True)

C:\Users\usuario\AppData\Local\Temp\ipykernel_12448\2659043205.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data2['history_of_fever'].fillna(0 , inplace=True)


In [171]:
any_null_cols_2 = data2.columns[data2.isnull().any()]
data2[any_null_cols_2].isnull().sum()

fever_temperature    1217
oxygen_saturation       4
dtype: int64

### Fever_Temperature

Para imputar los valores de 'fever_temperature', intentaremos crear un modelo de regresión con todas las demás variables numéricas, y según su R^2 lo utilizaremos o no.

In [172]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

fever_temperature_data = data2.dropna(subset=['fever_temperature'])
X = fever_temperature_data.drop(['patient_id', 'fever_temperature', 'date_of_first_symptoms', 'oxygen_saturation'], axis=1)
y = fever_temperature_data['fever_temperature']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression
fever_temperature_LR = LinearRegression()
fever_temperature_LR.fit(X_train, y_train)

predicted_fever_temperature_LR = fever_temperature_LR.predict(X_test)

# SVR
fever_temperature_SVR = SVR()
fever_temperature_SVR.fit(X_train, y_train)

predicted_fever_temperature_SVR = fever_temperature_SVR.predict(X_test)

In [173]:
from sklearn.metrics import r2_score

print("El R2 score para el modelo de Regresión Lineal es", r2_score(y_test, predicted_fever_temperature_LR))
print("El R2 score para el modelo de SVR es", r2_score(y_test, predicted_fever_temperature_SVR))

El R2 score para el modelo de Regresión Lineal es -0.008381711132781966
El R2 score para el modelo de SVR es -0.057437612813711736


Como vemos, los modelos creados tienen un R2 incluso negativo, es decir, no sirven de absolutamente nada. De hecho, son peores que la imputación con la media. Por tanto, vamos a realizar una imputación con la media.

Antes de imputar nos aseguramos de que no haya ningún dato nulo escondido como un dato normal (por ejemplo, un -1), y para ello veremos el rango en el que se mueve, que deberían de ser valores cercanos a 37.

In [174]:
data2['fever_temperature'].value_counts().sort_index()

fever_temperature
34.8    1
34.9    1
35.0    2
35.1    1
35.2    1
       ..
39.4    3
39.4    4
39.5    1
39.6    4
40.1    1
Name: count, Length: 62, dtype: int64

Como vemos, los datos están en un rango esperado, por tanto, podemos seguir con la imputación de los datos.

In [175]:
data2['fever_temperature'] = data2['fever_temperature'].fillna(data2['fever_temperature'].mean())

In [176]:
any_null_cols_2 = data2.columns[data2.isnull().any()]
data2[any_null_cols_2].isnull().sum()

oxygen_saturation    4
dtype: int64

### Oxygen Saturation

In [178]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

oxygen_saturation = data2.dropna(subset=['oxygen_saturation'])
X = oxygen_saturation.drop(['patient_id', 'fever_temperature', 'date_of_first_symptoms', 'oxygen_saturation'], axis=1)
y = oxygen_saturation['oxygen_saturation']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression
oxygen_saturation_LR = LinearRegression()
oxygen_saturation_LR.fit(X_train, y_train)

predicted_oxygen_saturation_LR = oxygen_saturation_LR.predict(X_test)

# SVR
oxygen_saturation_SVR = SVR()
oxygen_saturation_SVR.fit(X_train, y_train)

predicted_oxygen_saturation_SVR = oxygen_saturation_SVR.predict(X_test)

In [179]:
print("El R2 score para el modelo de Regresión Lineal es", r2_score(y_test, predicted_oxygen_saturation_LR))
print("El R2 score para el modelo de SVR es", r2_score(y_test, predicted_oxygen_saturation_SVR))

El R2 score para el modelo de Regresión Lineal es -0.002269860473276708
El R2 score para el modelo de SVR es -0.034064576353530995


De nuevo volvemos a apreciar que los valores son negativos, lo que significa que los modelos no van a ser capaces de explicar la variabilidad y volvemos a seleccionar la media.

Antes de ello, volvemos a comprobar que no haya algún valor que realmente sea nulo, como por ejemplo los valores 0 y -1, ya que el nivel de saturación en una persona sana es entre el 95% y el 100%.

In [180]:
data2['oxygen_saturation'].value_counts().sort_index()

oxygen_saturation
-1.0        16
 0.0        49
 68.0        1
 69.0        3
 70.0       11
 71.0        6
 73.0        1
 76.0        2
 77.0       22
 78.0       56
 79.0       96
 80.0      153
 81.0       50
 82.0       27
 83.0        7
 84.0       29
 85.0      104
 86.0      171
 87.0      258
 88.0      486
 89.0      618
 90.0      369
 91.0      201
 92.0      123
 93.0      117
 94.0      827
 95.0     2747
 96.0     3112
 97.0     1527
 98.0     1033
 99.0      417
 100.0      58
Name: count, dtype: int64

Existen valores de -1 y 0. Ambos valores no son válidos y, por tanto, los consideramos nulos.

In [181]:
import numpy as np
data2.loc[data2['oxygen_saturation'].isin([-1, 0]), 'oxygen_saturation'] = np.nan

In [182]:
data2['oxygen_saturation'].value_counts().sort_index()

oxygen_saturation
68.0        1
69.0        3
70.0       11
71.0        6
73.0        1
76.0        2
77.0       22
78.0       56
79.0       96
80.0      153
81.0       50
82.0       27
83.0        7
84.0       29
85.0      104
86.0      171
87.0      258
88.0      486
89.0      618
90.0      369
91.0      201
92.0      123
93.0      117
94.0      827
95.0     2747
96.0     3112
97.0     1527
98.0     1033
99.0      417
100.0      58
Name: count, dtype: int64

Ahora podemos observar los valores reales de la distribución. Sin embargo, también se registran valores significativamente bajos, cercanos al 70%, lo que podría estar relacionado con alguna condición médica grave.

In [183]:
data2['oxygen_saturation'].isna().sum()

69

Hemos pasado de tener 4 valores nulos a tener 69 nulos. Como hicimos antes, vamos a imputar los valores con la media.

In [184]:
data2['oxygen_saturation'] = data2['oxygen_saturation'].fillna(data2['oxygen_saturation'].mean())

Así, ya hemos acabado con el tratamiento de nulos y ya no existen nulos en los datos.

De igual manera, como hemos visto, existen valores con -1, lo que indica que son valores nulos. Por tanto, vamos a revisar que no exista este caso en el resto del dataset.

In [185]:
data2[data2 == -1].count()

patient_id                         0
x0_Azerbaijan                      0
x0_Other                           0
x0_T.C.                            0
age                                1
sex                                0
date_of_first_symptoms             0
fever_temperature                  0
oxygen_saturation                  0
history_of_fever                   0
cough                              0
sore_throat                        0
runny_nose                         0
wheezing                           0
shortness_of_breath                0
lower_chest_wall_indrawing         0
chest_pain                         0
conjunctivitis                     0
lymphadenopathy                    0
headache                           0
loss_of_smell                      0
loss_of_taste                      0
fatigue_malaise                    0
anorexia                           0
altered_consciousness_confusion    0
muscle_aches                       0
joint_pain                         0
i

Vemos, que solo existe un caso en la columna "age". Por tanto, vamos a hacer como antes, lo transformamos a nulo e imputamos el valor con la media.

In [186]:
data2.loc[data2['age'].isin([-1]), 'age'] = np.nan

In [187]:
data2['age'] = data2['age'].fillna(data2['age'].mean())

In [188]:
data2['age'].value_counts().sort_index()

age
0.0      1
1.0      1
4.0      1
6.0      1
8.0      1
        ..
91.0     3
92.0     6
93.0     2
94.0     2
100.0    1
Name: count, Length: 93, dtype: int64

Así, presuntamente, todos los valores son válidos

In [189]:
data2.groupby('patient_id')['date_of_first_symptoms'].nunique()

patient_id
714         1
4809        1
15834       1
16047       1
35690       1
           ..
99939799    1
99947088    1
99955706    1
99976931    1
99993034    1
Name: date_of_first_symptoms, Length: 9401, dtype: int64

In [190]:
pd.set_option('display.max_columns', None)

In [191]:
data2[data2.duplicated(subset=['patient_id', 'date_of_first_symptoms'], keep=False)].sort_values(by=['patient_id', 'date_of_first_symptoms'])

Empty DataFrame
Columns: [patient_id, x0_Azerbaijan, x0_Other, x0_T.C., age, sex, date_of_first_symptoms, fever_temperature, oxygen_saturation, history_of_fever, cough, sore_throat, runny_nose, wheezing, shortness_of_breath, lower_chest_wall_indrawing, chest_pain, conjunctivitis, lymphadenopathy, headache, loss_of_smell, loss_of_taste, fatigue_malaise, anorexia, altered_consciousness_confusion, muscle_aches, joint_pain, inability_to_walk, abdominal_pain, diarrhoea, vomiting_nausea, skin_rash, bleeding, other_symptoms, chronic_cardiac_disease, hypertension, chronic_pulmonary_disease, asthma, chronic_kidney_disease, obesity, liver_disease, asplenia, chronic_neurological_disorder, malignant_neoplasm, chronic_hematologic_disease, AIDS_HIV, diabetes_mellitus_type_1, diabetes_mellitus_type_2, rheumatologic_disorder, dementia, tuberculosis, smoking, other_risks, PCR_result]
Index: []

Observamos, que no hay filas duplicadas basándonas en las columnas del ID y la fecha de los primeros síntomas.